export const MENU_ITEMS = [
    {
        id: '1',
        day: 'Monday',
        lunch: 'Paneer Butter Masala, Dal Tadka, Rice, 3 Rotis, Salad',
        dinner: 'Aloo Gobi, Dal Fry, Rice, 3 Rotis, Pickle',
        image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800',
        rating: 4.5,
    },
    {
        id: '2',
        day: 'Tuesday',
        lunch: 'Rajma Chawal, Jeera Aloo, 3 Rotis, Raita',
        dinner: 'Bhindi Masala, Dal Makhani, Rice, 3 Rotis, Salad',
        image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800',
        rating: 4.7,
    },
    {
        id: '3',
        day: 'Wednesday',
        lunch: 'Chole Bhature, Rice, Salad, Pickle',
        dinner: 'Mix Veg, Dal Tadka, Rice, 3 Rotis, Sweet',
        image: 'https://images.unsplash.com/photo-1626132647523-66f0bf380027?w=800',
        rating: 4.8,
    },
    {
        id: '4',
        day: 'Thursday',
        lunch: 'Kadhi Pakora, Rice, Aloo Jeera, 3 Rotis',
        dinner: 'Egg Curry / Paneer Curry, Rice, 3 Rotis, Salad',
        image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800',
        rating: 4.6,
    },
    {
        id: '5',
        day: 'Friday',
        lunch: 'Dal Makhani, Shahi Paneer, Naan, Rice',
        dinner: 'Soyabean Curry, Dal Fry, Rice, 3 Rotis',
        image: 'https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=800',
        rating: 4.9,
    },
    {
        id: '6',
        day: 'Saturday',
        lunch: 'Veg Biryani, Raita, Salad, Papad',
        dinner: 'Malai Kofta, Naan, Rice, Salad',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800',
        rating: 4.8,
    },
    {
        id: '7',
        day: 'Sunday',
        lunch: 'Special Thali (3 Sabzi, Dal, Rice, Sweet)',
        dinner: 'Light Khichdi / Dalia, Papad, Pickle',
        image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=800',
        rating: 5.0,
    },
];
